import Head from 'next/head';
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Baseball Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>baseball frontend</p>

        <Link href="/account/signin">
          로그인
        </Link>

        <Link href="/account/signup">
          회원가입
        </Link>
      </main>
    </>
  );
}
